### ISSUE TITLE
hit endpoint backend untuk membuat pemeriksaan pasien baru

### ISSUE THREAD

**Issue by maybeenang** [sonjecomp/labkesda-mobile-flutter#36]
tolong hit api untuk membuat pemeriksaan untuk bagian pasien baru

**Comment by henhen02** [comment]
> tolong hit api untuk membuat pemeriksaan untuk bagian pasien baru

# Siap Pak, besok saja ya. Saya lagi mager, istri saya udah ngambek soalnya hehe
